config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :contacts
    resources :services
    resources :users
  end
  resources :admin, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'main#index'

  namespace :v1, defaults: { format: :json } do
    post "token_login" => "sessions#token_login"
    post "login" => "sessions#create"
    post "cadastro" => "registrations#create"
    post "google_oauth2" => "sessions#google_oauth2"
    post "upload_avatar" => "users#upload_avatar"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /admin/services
  # GET /admin/services.json
  def index
    @services = Service.all
  end

  # GET /admin/services/1
  # GET /admin/services/1.json
  def show
  end

  # GET /admin/services/new
  def new
    @service = Service.new
  end

  # GET /admin/services/1/edit
  def edit
  end

  # POST /admin/services
  # POST /admin/services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to [:admin, @service], notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/services/1
  # PATCH/PUT /admin/services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to [:admin, @service], notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/services/1
  # DELETE /admin/services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to admin_services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description)
    end
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/views/admin/services/_form.html.erb
<%= simple_form_for([:admin, @service]) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-group">
    <%= f.input :name, input_html: { class: "form-control" } %>
    <%= f.input :description, input_html: { class: "form-control" } %>
</div>

<div class="form-group">
  <%= f.button :submit, class: "btn btn-success" %>
</div>
<% end %>

app/views/admin/services/edit.html.erb
<div class="page-header">
  <h1>Editing service</h1>
  <hr>
</div>

<div class="card">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Show', [:admin, @service], class: 'btn btn-primary' %>
<%= link_to 'Back', admin_services_path, class: 'btn btn-secondary' %>

app/views/admin/services/index.html.erb
<div class="page-header">
  <h1>Listing services</h1>
  <hr>
</div>

<div class="card">
  <div class="card-body">
    <table class="table table-hover" id="table-services">
      <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Ver</th>
        <th>Editar</th>
        <th>Deletar</th>
      </tr>
      </thead>

      <tbody>
      <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= link_to 'Show', [:admin, service], class: 'btn btn-outline-info btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admin_service_path(service), class: 'btn btn-outline-warning btn-xs' %></td>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, [:admin, service], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-outline-danger' %></td>
      </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>
<br>

<%= link_to 'New Service', new_admin_service_path, class: 'btn btn-outline-primary' %>

<script>
    let service_table = null;
    document.addEventListener("turbolinks:load", function(){
        service_table = $('#table-services').DataTable(
            {
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Nada encontrado",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhuma data encontrada",
                    "infoFiltered": "(filtrando _MAX_ de um total de registros)",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Próxima",
                    },
                    "search": "Procurar"
                }
            }
        );
    });

    document.addEventListener("turbolinks:before-cache", function () {
        if($('#table-services').length == 1){
            service_table.destroy();
        }
    });
</script>

app/views/admin/services/new.html.erb
<div class="page-header">
  <h1>New service</h1>
  <hr>
</div>

<div class="card">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', admin_services_path, class: 'btn btn-default' %>

app/views/admin/services/show.html.erb
<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @service.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Description:</strong></dt>
  <dd><%= @service.description %></dd>
</dl>

<%= link_to 'Edit', edit_admin_service_path(@service), class: 'btn btn-outline-warning' %>
<%= link_to 'Back', admin_services_path, class: 'btn btn-secondary' %>