config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :contacts
    resources :services
    resources :users
  end
  resources :admin, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'main#index'

  namespace :v1, defaults: { format: :json } do
    post "token_login" => "sessions#token_login"
    post "login" => "sessions#create"
    post "cadastro" => "registrations#create"
    post "google_oauth2" => "sessions#google_oauth2"
    post "upload_avatar" => "users#upload_avatar"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validate :check_record, on: :create #please not that validate in this case is singular

  def check_record
    Contact.test
    if Contact.all.count >= 1
      errors[:base] << "You can only have one active contact"
    end
  end

  def self.test
    puts "Test"
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Rails.application.routes.url_helpers
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum provider: [:google, :facebook]

  after_create :update_user_token!
  has_one_attached :avatar

  def as_json(options = {})
    {
      id: id,
      first_name: first_name,
      last_name: last_name,
      token: token,
      email: email,
      provider: provider,
      avatar: user_avatar
    }
  end

  def user_avatar
    if self.avatar.attached?
      url_for(self.avatar)
    elsif self.avatar_url
      self.avatar_url
    else
      ""
    end
  end

  def is_admin?
    has_role? :admin
  end

  require 'securerandom'
  def self.from_google(provider, user_data, token)
    where(provider: provider, uid: user_data['id']).first_or_create do |user|
      user.uid = user_data['id']
      user.token = token
      user.email = user_data['email']
      user.first_name = user_data['first_name']
      user.last_name = user_data['last_name']
      user.avatar_url = user_data['avatar_url']
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def update_user_token!
    if self.token.nil?
      self.token = Devise.friendly_token
      self.save
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :require_admin!
  def index
  end

  def require_admin!
    unless user_signed_in? and current_user.is_admin?
      flash[:danger] = "Apenas administradores tem acesso à essa área."
      redirect_to root_path
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session
  include AbstractController::Translation
  respond_to :json

  def current_user
    @current_user ||= authenticate_token
  end

  private

  def authenticate_token
    auth_token = request.headers['Authorization']
    @user = User.find_by(token: auth_token)
    @user
  end

  ##
  # Authentication Failure
  # Renders a 401 error
  def authentication_error
    # User's token is either invalid or not in the right format
    render json: {error: t('unauthorized')}, status: 401 # Authentication timeout
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_admin?
      admin_index_path
    else
      root_path
    end
  end

  def after_update_path_for(resource_or_scope)
    if resource_or_scope.is_admin?
      admin_index_path
    else
      root_path
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @contact = Contact.last
  end
end

app/controllers/v1/users_controller.rb
# Controller para gerenciamento de usuários na API
module V1
  class UsersController < ApiController
    def upload_avatar
      current_user.avatar.attach(io: image_io, filename: image_name)

      if current_user.save
        render json: { msg: "Avatar updated" }, status: 200
      else
        puts current_user.errors.inspect
        render json: { msg: "Unable to update avatar" }, status: 422
      end
    end

    private

    def image_io
      decoded_image = Base64.decode64(params[:avatar][:image])
      StringIO.new(decoded_image)
    end

    def image_name
      params[:avatar][:file_name]
    end
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/v1/registrations_helper.rb
module V1::RegistrationsHelper
end

app/helpers/v1/sessions_helper.rb
module V1::SessionsHelper
end

app/helpers/v1/users_helper.rb
module V1::UsersHelper
end

app/views/admin/index.html.erb
<h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Starter | Admin</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>

  <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
    <% flash.each do |key, value| %>
      <% if key == 'alert' %>
        <% key = 'danger' %>
      <% elsif key == 'notice' %>
        <% key = 'success' %>
      <% end %>
      <div class="alert alert-<%= key %>" style="position: absolute; top: 20px; left: 20px; z-index: 999;"> <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true" style="margin-left: 5px;"> &times;</span> </button>
      </div>
    <% end %>
    <%= render 'layouts/admin/navbar' %>
    <div id="content-wrapper" class="d-flex flex-column">
      <%= render 'layouts/admin/header' %>
      <div id="content">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
      <%= render 'layouts/admin/footer' %>
    </div>
  </div>
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/admin/_footer.html.erb
<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Your Website 2019</span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fa fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fa fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alerts Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fa fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fa fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fa fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
            <div class="status-indicator"></div>
          </div>
          <div>
            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
            <div class="status-indicator bg-warning"></div>
          </div>
          <div>
            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
      </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.full_name %></span>
        <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fa fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>

  </ul>

</nav>
<!-- End of Topbar -->

app/views/layouts/admin/_navbar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fa fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <a class="nav-link" href="<%= admin_index_path %>">
      <i class="fa fa-fw fa-dashboard"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Interface
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fa fa-fw fa-users"></i>
      <span>Users</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item" href="<%= admin_users_path %>">Manage</a>
      </div>
    </div>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="<%= admin_contacts_path %>">
      <i class="fa fa-fw fa-cog"></i>
      <span>Contact</span></a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="<%= admin_services_path %>">
      <i class="fa fa-fw fa-server"></i>
      <span>Services</span></a>
  </li>

</ul>
<!-- End of Sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <% if key == 'alert' %>
        <% key = 'danger' %>
      <% elsif key == 'notice' %>
        <% key = 'success' %>
      <% end %>
      <div class="alert alert-<%= key %>" style="position: absolute; top: 20px; left: 20px; z-index: 999;"> <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true" style="margin-left: 5px;"> &times;</span> </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>