config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :contacts
    resources :services
    resources :users
  end
  resources :admin, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'main#index'

  namespace :v1, defaults: { format: :json } do
    post "token_login" => "sessions#token_login"
    post "login" => "sessions#create"
    post "cadastro" => "registrations#create"
    post "google_oauth2" => "sessions#google_oauth2"
    post "upload_avatar" => "users#upload_avatar"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  validate :check_record, on: :create #please not that validate in this case is singular

  def check_record
    Contact.test
    if Contact.all.count >= 1
      errors[:base] << "You can only have one active contact"
    end
  end

  def self.test
    puts "Test"
  end
end

app/controllers/admin/contacts_controller.rb
module Admin
  class ContactsController < AdminController
    before_action :set_contact, only: [:show, :edit, :update, :destroy]

    # GET /admin/contacts
    # GET /admin/contacts.json
    def index
      @contacts = Contact.all
    end

    # GET /admin/contacts/1
    # GET /admin/contacts/1.json
    def show
    end

    # GET /admin/contacts/new
    def new
      @contact = Contact.new
    end

    # GET /admin/contacts/1/edit
    def edit
    end

    # POST /admin/contacts
    # POST /admin/contacts.json
    def create
      @contact = Contact.new(contact_params)

      respond_to do |format|
        if @contact.save
          format.html { redirect_to admin_contacts_path, notice: 'Contact was successfully created.' }
          format.json { render action: 'show', status: :created, location: @contact }
        else
          format.html { render action: 'new' }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/contacts/1
    # PATCH/PUT /admin/contacts/1.json
    def update
      respond_to do |format|
        if @contact.update(contact_params)
          format.html { redirect_to [:admin, @contact], notice: 'Contact was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/contacts/1
    # DELETE /admin/contacts/1.json
    def destroy
      @contact.destroy
      respond_to do |format|
        format.html { redirect_to admin_contacts_url, notice: 'Contact was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone)
    end
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/views/admin/contacts/_form.html.erb
<%= form_for([:admin, @contact]) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br>
    <%= f.text_field :name %>
    </div>
  <div class="field">
      <%= f.label :email %><br>
    <%= f.text_field :email %>
    </div>
  <div class="field">
      <%= f.label :phone %><br>
    <%= f.text_field :phone %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @contact] %> |
<%= link_to 'Back', admin_contacts_path %>

app/views/admin/contacts/index.html.erb
<div class="card">
  <div class="card-body">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.phone %></td>
          <td><%= link_to 'Show', [:admin, contact], class: "btn btn-outline-primary" %></td>
          <td><%= link_to 'Edit', edit_admin_contact_path(contact), class: "btn btn-outline-warning" %></td>
          <td><%= link_to 'Destroy', [:admin, contact], class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/admin/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_contacts_path %>

app/views/admin/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<%= link_to 'Edit', edit_admin_contact_path(@contact) %> |
<%= link_to 'Back', admin_contacts_path %>