config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :contacts
    resources :services
    resources :users
  end
  resources :admin, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'main#index'

  namespace :v1, defaults: { format: :json } do
    post "token_login" => "sessions#token_login"
    post "login" => "sessions#create"
    post "cadastro" => "registrations#create"
    post "google_oauth2" => "sessions#google_oauth2"
    post "upload_avatar" => "users#upload_avatar"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Rails.application.routes.url_helpers
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum provider: [:google, :facebook]

  after_create :update_user_token!
  has_one_attached :avatar

  def as_json(options = {})
    {
      id: id,
      first_name: first_name,
      last_name: last_name,
      token: token,
      email: email,
      provider: provider,
      avatar: user_avatar
    }
  end

  def user_avatar
    if self.avatar.attached?
      url_for(self.avatar)
    elsif self.avatar_url
      self.avatar_url
    else
      ""
    end
  end

  def is_admin?
    has_role? :admin
  end

  require 'securerandom'
  def self.from_google(provider, user_data, token)
    where(provider: provider, uid: user_data['id']).first_or_create do |user|
      user.uid = user_data['id']
      user.token = token
      user.email = user_data['email']
      user.first_name = user_data['first_name']
      user.last_name = user_data['last_name']
      user.avatar_url = user_data['avatar_url']
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def update_user_token!
    if self.token.nil?
      self.token = Devise.friendly_token
      self.save
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def sign_up_params
    params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :first_name,
        :last_name,
        )
  end

  def account_update_params
    params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :first_name,
        :last_name,
        )
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/v1/users_controller.rb
# Controller para gerenciamento de usuários na API
module V1
  class UsersController < ApiController
    def upload_avatar
      current_user.avatar.attach(io: image_io, filename: image_name)

      if current_user.save
        render json: { msg: "Avatar updated" }, status: 200
      else
        puts current_user.errors.inspect
        render json: { msg: "Unable to update avatar" }, status: 422
      end
    end

    private

    def image_io
      decoded_image = Base64.decode64(params[:avatar][:image])
      StringIO.new(decoded_image)
    end

    def image_name
      params[:avatar][:file_name]
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/v1/users_helper.rb
module V1::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for([:admin, @user]) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-group">
    <%= f.input :first_name, input_html: { class: "form-control" } %>
    <%= f.input :last_name, input_html: { class: "form-control" } %>
    <%= f.input :email, input_html: { class: "form-control" } %>
</div>

<div class="form-group">
  <%= f.button :submit, class: "btn btn-success" %>
</div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h1>Editing user</h1>
  <hr>
</div>

<div class="card">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Show', [:admin, @user], class: 'btn btn-primary' %>
<%= link_to 'Back', admin_users_path, class: 'btn btn-secondary' %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Listing users</h1>
  <hr>
</div>

<div class="card">
  <div class="card-body">
    <table class="table table-hover" id="table-users">
      <thead>
      <tr>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Ver</th>
        <th>Editar</th>
        <th>Deletar</th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
      <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.email %></td>
                <td><%= link_to 'Show', [:admin, user], class: 'btn btn-outline-info btn-xs' %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-outline-warning btn-xs' %></td>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, [:admin, user], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-outline-danger' %></td>
      </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>
<br>

<%= link_to 'New User', new_admin_user_path, class: 'btn btn-outline-primary' %>

<script>
    let user_table = null;
    document.addEventListener("turbolinks:load", function(){
        user_table = $('#table-users').DataTable(
            {
                "language": {
                    "lengthMenu": "Mostrar _MENU_ registros por página",
                    "zeroRecords": "Nada encontrado",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhuma data encontrada",
                    "infoFiltered": "(filtrando _MAX_ de um total de registros)",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Próxima",
                    },
                    "search": "Procurar"
                }
            }
        );
    });

    document.addEventListener("turbolinks:before-cache", function () {
        if($('#table-users').length == 1){
            user_table.destroy();
        }
    });
</script>

app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>New user</h1>
  <hr>
</div>

<div class="card">
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', admin_users_path, class: 'btn btn-default' %>

app/views/admin/users/show.html.erb
<dl class="dl-horizontal">
  <dt><strong>First name:</strong></dt>
  <dd><%= @user.first_name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Last name:</strong></dt>
  <dd><%= @user.last_name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Email:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<%= link_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-outline-warning' %>
<%= link_to 'Back', admin_users_path, class: 'btn btn-secondary' %>